// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart'; // <--- 1. Import Added

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // 2. Changed from 'static const' to 'static FirebaseOptions get'
  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['Android_KEY']!, // <--- 3. Using Secure Env Variable
    appId: '1:43870521160:android:5d99464f74ca45d3b5157d',
    messagingSenderId: '43870521160',
    projectId: 'running-tracker-48dcf',
    storageBucket: 'running-tracker-48dcf.firebasestorage.app',
  );

  // 2. Changed from 'static const' to 'static FirebaseOptions get'
  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['IOS_KEY']!, // <--- 3. Using Secure Env Variable
    appId: '1:43870521160:ios:2d170af7d61c4273b5157d',
    messagingSenderId: '43870521160',
    projectId: 'running-tracker-48dcf',
    storageBucket: 'running-tracker-48dcf.firebasestorage.app',
    iosBundleId: 'com.example.runApp',
  );
}